name: PyTest

on: push
    
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v1

    - name: Install Dependencies
      run: pip install -r requirements.txt

    - name: Run Tests
      run: pytest
